name: WildFly Scan

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run at 6:13 every day
  schedule:
     - cron: "13 6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan-matrix:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        version: [38.0.1.Final, 39.0.1.Final, 40.0.1.Final, 40.0.1.Final-EE10, 41.0.0.Final, 41.0.0.Final-EE10, 41.0.0.Final-Preview, standard-upstream, preview-upstream, standard-maintenance, ee10-maintenance, preview-maintenance]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Cache the instllation
      - name: Cache WildFly Installation
        if: ${{ !contains(matrix.version, 'maintenance') || vars.MAINTENANCE_CI != 'OFF' }}
        id: wildfly-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/wildfly
          key: wildfly-${{ matrix.version}}
          restore-keys: wildfly-${{ matrix.version}}-   # Distributions based on nightly runs use unique suffix in cache name.
          fail-on-cache-miss: true

      # Restore Dependency Check CLI from Cache
      - name: Cache Dependency Check Installation
        if: ${{ !contains(matrix.version, 'maintenance') || vars.MAINTENANCE_CI != 'OFF' }}
        id: dependency-check-cli-installation
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/dependency-check
          key: dependency-check-${{ vars.DEPENDENCY_CHECK_VERSION }}
          fail-on-cache-miss: true

      # Caching for the Dependency Check Database
      #
      # A we have a unique run IT / Attempt we will never restore
      # using the key, instead we restore the most recent and save
      # using the unique key.
      - name: Cache Dependency Check Database
        if: ${{ !contains(matrix.version, 'maintenance') || vars.MAINTENANCE_CI != 'OFF' }}
        id: cache-database
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/owasp-database
          key: owasp-database-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index}}
          restore-keys: owasp-database-

      # Populate a properties file with secrets
      - name: Populate Dependency Check Properties
        if: ${{ !contains(matrix.version, 'maintenance') || vars.MAINTENANCE_CI != 'OFF' }}
        run: |
          if [ "${{ vars.SONATYPE_OSS_INDEX }}" == "OFF" ]; then
            echo "analyzer.ossindex.enabled=false" > dependency-check.properties
          else
            echo "analyzer.ossindex.password=${{ secrets.OSS_INDEX_PASSWORD }}" > dependency-check.properties
          fi
          ls -l
          cat dependency-check.properties

      # Perform SCA Scan
      - name: Perform SCA Scan
        if: ${{ !contains(matrix.version, 'maintenance') || vars.MAINTENANCE_CI != 'OFF' }}
        run: |
          OSS_ARGS=""
          if [ "${{ vars.SONATYPE_OSS_INDEX }}" != "OFF" ]; then
            OSS_ARGS="--ossIndexUsername=${{ secrets.OSS_INDEX_USERNAME }}"
          fi
          ./dependency-check/bin/dependency-check.sh --project="WildFly ${{ matrix.version}}" --scan="wildfly" --noupdate --suppression=owasp-suppressions/owasp-suppressions.xml --data=owasp-database --format=HTML --format=JSON --nvdApiKey=${{ secrets.NVD_API_KEY }} $OSS_ARGS --propertyfile=dependency-check.properties --log=dependency-check.log

      # Upload the log files
      - name: Upload Scan Results
        if: ${{ success() && (!contains(matrix.version, 'maintenance') || vars.MAINTENANCE_CI != 'OFF') }}
        uses: actions/upload-artifact@v4
        with:
          name: scan-results-${{ matrix.version }}
          path: ${{ github.workspace }}/dependency-check-report.*

      # Upload the log files
      - name: Upload Log File
        if: ${{ failure() && (!contains(matrix.version, 'maintenance') || vars.MAINTENANCE_CI != 'OFF') }}
        uses: actions/upload-artifact@v4
        with:
          name: log-files-${{ matrix.version }}
          path: ~/work/**/*.log
